module.exports = {
  front: [
    "README",
    {
      type: "category",
      label: "书籍",
      items: ["Books/clean-code-javascript"],
    },
    {
      type: "category",
      label: "HTML",
      items: ["HTML/meta"],
    },
    {
      type: "category",
      label: "CSS",
      items: ["CSS/common", "CSS/skill", "CSS/flex/flex", "CSS/interview"],
    },
    {
      type: "category",
      label: "JavaScript",
      items: [
        {
          type: "category",
          label: "数据类型",
          items: [
            "JavaScript/types/general",
            "JavaScript/types/null-undefined-boolean",
            "JavaScript/types/number",
            "JavaScript/types/string",
            "JavaScript/types/object",
            "JavaScript/types/function",
            "JavaScript/types/array",
          ],
        },
        {
          type: "category",
          label: "运算符",
          items: [
            "JavaScript/operators/arithmetic",
            "JavaScript/operators/comparison",
            "JavaScript/operators/boolean",
            "JavaScript/operators/bit",
            "JavaScript/operators/priority",
          ],
        },
        {
          type: "category",
          label: "标准库",
          items: [
            "JavaScript/stdlib/object",
            "JavaScript/stdlib/attributes",
            "JavaScript/stdlib/array",
            "JavaScript/stdlib/wrapper",
            "JavaScript/stdlib/boolean",
            "JavaScript/stdlib/number",
            "JavaScript/stdlib/string",
            "JavaScript/stdlib/math",
            "JavaScript/stdlib/date",
          ],
        },
        {
          type: "category",
          label: "BOM",
          items: ["JavaScript/bom/window"],
        },
        "JavaScript/common",
        "JavaScript/handwritten",
        "JavaScript/thanks",
      ],
    },
    {
      type: "category",
      label: "ES6",
      items: ["ES6/let", "ES6/symbol", "ES6/module", "ES6/module-loader"],
    },
    {
      type: "category",
      label: "TypeScript",
      items: [
        "TypeScript/quickstart",
        "TypeScript/basic-types",
        "TypeScript/interfaces",
        "TypeScript/class",
        "TypeScript/function",
        "TypeScript/generics",
        "TypeScript/enums",
        "TypeScript/advanced-types",
        "TypeScript/lint",
        "TypeScript/thanks",
      ],
    },
    {
      type: "category",
      label: "Web API",
      items: ["WebAPI/file", "WebAPI/thanks"],
    },
    {
      type: "category",
      label: "设计模式",
      items: [
        "Design-Pattern/Abstract-Factory",
        "Design-Pattern/Observer",
        "Design-Pattern/Strategy",
      ],
    },
    {
      type: "category",
      label: "Vue",
      items: ["Vue/Vue3", "Vue/Vuex", "Vue/Vue-Cli"],
    },
    {
      type: "category",
      label: "工程化",
      items: ["Engineering/Vue3"],
    },
    "Performance-Optimization/Performance-Optimization",
    "Security",
    {
      type: "category",
      label: "Axios",
      items: ["Axios/Axios", "Axios/axios-refeshToken"],
    },
    "Redux/Redux",
    "Element-UI",
    "Jlc-UI/Jlc-UI",
    {
      type: "category",
      label: "Vite",
      items: ["Vite/Vite", "Vite/md-to-vue"],
    },
    "NPM",
    "Sass",
    "Jest",
    "Cli/Cli",
    "Gulp",
    "Prettierrc",
    {
      type: "category",
      label: "开发",
      items: ["Develop/Attention", "Develop/Token"],
    },
    {
      type: "category",
      label: "Git",
      items: ["Git/Git"],
    },
    {
      type: "category",
      label: "Github",
      items: ["Github/ssh"],
    },
    "Interview",
    "Navigation",
    "WebStorm",
    "Webpack",
    "Fiddler/Fiddler",
  ],
  end: ["Node", "Express"],
};
