module.exports = {
  front: [
    "README",
    {
      type: "category",
      label: "书籍",
      items: ["Books/clean-code-javascript"],
    },
    {
      type: "category",
      label: "HTML",
      items: ["HTML/meta"],
    },
    {
      type: "category",
      label: "CSS",
      items: ["CSS/common", "CSS/skill", "CSS/flex/flex"],
    },
    {
      type: "category",
      label: "JavaScript",
      items: [
        "JavaScript/common",
        {
          type: "category",
          label: "数据类型",
          items: [
            "JavaScript/types/general",
            "JavaScript/types/null-undefined-boolean",
            "JavaScript/types/number",
            "JavaScript/types/string",
            "JavaScript/types/object",
            "JavaScript/types/function",
            "JavaScript/types/array",
          ],
        },
        {
          type: "category",
          label: "运算符",
          items: [
            "JavaScript/operators/arithmetic",
            "JavaScript/operators/comparison",
            "JavaScript/operators/boolean",
            "JavaScript/operators/bit",
            "JavaScript/operators/priority",
          ],
        },
        {
          type: "category",
          label: "标准库",
          items: ["JavaScript/stdlib/array"],
        },
        {
          type: "category",
          label: "BOM",
          items: ["JavaScript/bom/window"],
        },
        "JavaScript/thanks",
      ],
    },
    {
      type: "category",
      label: "ES6",
      items: ["ES6/symbol", "ES6/module", "ES6/module-loader"],
    },
    {
      type: "category",
      label: "TypeScript",
      items: [
        "TypeScript/quickstart",
        "TypeScript/basic-types",
        "TypeScript/interfaces",
        "TypeScript/class",
        "TypeScript/function",
        "TypeScript/generics",
        "TypeScript/enums",
        "TypeScript/advanced-types",
        "TypeScript/lint",
        "TypeScript/thanks",
      ],
    },
    {
      type: "category",
      label: "Web API",
      items: ["WebAPI/file", "WebAPI/thanks"],
    },
    {
      type: "category",
      label: "Vue",
      items: ["Vue/Vue3"],
    },
    {
      type: "category",
      label: "工程化",
      items: ["Engineering/Vue3"],
    },
    "Axios",
    "Redux/Redux",
    "Element-UI",
    "Jlc-UI/Jlc-UI",
    "Vite",
    "NPM",
    "Cli/Cli",
    "Gulp",
    "Prettierrc",
    "DevelopAttention",
    "Interview",
    "Navigation",
    "WebStorm",
    "Fiddler/Fiddler",
  ],
  end: ["Node", "Express"],
};
